CREATE CACHED TABLE PUBLIC.USER(
    ID BIGINT id bigint auto_increment primary key,
    NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    NICK_NAME VARCHAR(255),
    PASSWORD VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255),
    COUNTRY VARCHAR(255)
)